name: DevOps
on: 
  push:
    branches: 
      - master
jobs:
   docker:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
            registry: registry.hub.docker.com
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
       - run: |
          docker build -t registry.hub.docker.com/sudipmondal2002/demo-shaastra .
          docker push registry.hub.docker.com/sudipmondal2002/demo-shaastra
      
